namespace MultipleChoiceTestsGenerator
{
    /// <summary>
    /// This class describes test dimensions form.
    /// </summary>
    public partial class TestDimensionsForm : Form
    {
        /// <summary>
        /// TestDimensionsForm default constructor.
        /// </summary>
        public TestDimensionsForm()
        {
            InitializeComponent();
            if (!InputValidator.IsValidNumberInput(questionsCountTextBox.Text)
                || !InputValidator.IsValidNumberInput(timeTextBox.Text)
                || studentNameTextBox.Text == "")
            {
                startTestButton.Enabled = false;
                return;
            }

            startTestButton.Enabled = true;
        }

        /// <summary>
        /// Starts the generated by the server test.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void startTestButton_Click(object sender, EventArgs e)
        {
            int questionsCount = int.Parse(questionsCountTextBox.Text);
            string studentName = studentNameTextBox.Text;
            int seconds = int.Parse(timeTextBox.Text);

            this.Hide();
            TestForm testForm = new TestForm(questionsCount, seconds, studentName);
            testForm.ShowDialog();
        }

        /// <summary>
        /// Validating the student name field on typing.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void studentNameTextBox_TextChanged(object sender, EventArgs e)
        {
            if (!InputValidator.IsValidNumberInput(questionsCountTextBox.Text)
                || !InputValidator.IsValidNumberInput(timeTextBox.Text)
                || studentNameTextBox.Text == "")
            {
                startTestButton.Enabled = false;
                return;
            }

            startTestButton.Enabled = true;
        }

        /// <summary>
        /// Validating the time in seconds field on typing.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void timeTextBox_TextChanged(object sender, EventArgs e)
        {
            if (!InputValidator.IsValidNumberInput(questionsCountTextBox.Text)
                || !InputValidator.IsValidNumberInput(timeTextBox.Text)
                || studentNameTextBox.Text == "")
            {
                startTestButton.Enabled = false;
                return;
            }

            startTestButton.Enabled = true;
        }

        /// <summary>
        /// Validating the questions count field on typing.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void questionsCountTextBox_TextChanged(object sender, EventArgs e)
        {
            if (!InputValidator.IsValidNumberInput(questionsCountTextBox.Text)
                || !InputValidator.IsValidNumberInput(timeTextBox.Text)
                || studentNameTextBox.Text == "")
            {
                startTestButton.Enabled = false;
                return;
            }

            startTestButton.Enabled = true;
        }
    }
}